-- Add all missing columns to branches table
ALTER TABLE "branches"
ADD COLUMN IF NOT EXISTS "address" VARCHAR,
ADD COLUMN IF NOT EXISTS "city" VARCHAR,
ADD COLUMN IF NOT EXISTS "state" VARCHAR,
ADD COLUMN IF NOT EXISTS "pincode" VARCHAR,
ADD COLUMN IF NOT EXISTS "phone" VARCHAR,
ADD COLUMN IF NOT EXISTS "email" VARCHAR,
ADD COLUMN IF NOT EXISTS "status" VARCHAR DEFAULT 'active',
ADD COLUMN IF NOT EXISTS "is_deleted" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS "created_by" UUID,
ADD COLUMN IF NOT EXISTS "updated_by" UUID,
ADD COLUMN IF NOT EXISTS "deleted_by" UUID,
ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ;