-- CreateTable (missing from baselined enterprise_registration migration)
CREATE TABLE IF NOT EXISTS "registration_sessions" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "email" VARCHAR NOT NULL,
    "email_verified" BOOLEAN DEFAULT false,
    "mobile" VARCHAR,
    "mobile_verified" BOOLEAN DEFAULT false,
    "first_name" VARCHAR,
    "last_name" VARCHAR,
    "display_name" VARCHAR,
    "country" VARCHAR,
    "timezone" VARCHAR,
    "language" VARCHAR,
    "gender" VARCHAR,
    "organization_name" VARCHAR,
    "organization_code" VARCHAR,
    "industry" VARCHAR,
    "size" VARCHAR,
    "website" VARCHAR,
    "gst_number" VARCHAR,
    "tax_number" VARCHAR,
    "logo_url" VARCHAR,
    "use_cases" JSONB,
    "branch_name" VARCHAR,
    "branch_code" VARCHAR,
    "branch_address" VARCHAR,
    "branch_city" VARCHAR,
    "branch_state" VARCHAR,
    "branch_country" VARCHAR,
    "branch_pincode" VARCHAR,
    "password_hash" VARCHAR,
    "mfa_enabled" BOOLEAN DEFAULT false,
    "mfa_method" VARCHAR,
    "mfa_secret" VARCHAR,
    "terms_accepted" BOOLEAN DEFAULT false,
    "privacy_accepted" BOOLEAN DEFAULT false,
    "cookie_accepted" BOOLEAN DEFAULT false,
    "marketing_consent" BOOLEAN DEFAULT false,
    "status" VARCHAR DEFAULT 'in_progress',
    "current_step" INTEGER DEFAULT 1,
    "ip_address" VARCHAR,
    "user_agent" VARCHAR,
    "expires_at" TIMESTAMPTZ,
    "completed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

-- AlterTable
ALTER TABLE "registration_sessions" ADD COLUMN IF NOT EXISTS "gender" VARCHAR;
