import { Router, type Response } from 'express';
import { authenticate, requirePermission, type AuthRequest } from '../../middleware/auth';
import { asyncHandler } from '../../middleware/async-handler';
import { orgContextOf } from '../../middleware/org-context';
import { BranchService } from './branch.service';
import {
  BranchListQuerySchema,
  CreateBranchSchema,
  IdParamSchema,
  UpdateBranchSchema,
} from './branch.dto';

const router = Router();
const service = new BranchService();

/**
 * @swagger
 * /api/v1/branches:
 *   get:
 *     summary: listBranches
 *     operationId: getBranches
 *     description: List branches of the caller's organization
 *     tags: [branches]
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - { in: query, name: q, schema: { type: string } }
 *       - { in: query, name: status, schema: { type: string, enum: [active, inactive] } }
 *       - { in: query, name: page, schema: { type: integer, minimum: 1 } }
 *       - { in: query, name: pageSize, schema: { type: integer, minimum: 1, maximum: 200 } }
 *     responses:
 *       200: { description: Paginated branches }
 */
router.get(
  '/',
  authenticate,
  requirePermission('users:read', 'users:manage'),
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = orgContextOf(req);
    const query = BranchListQuerySchema.parse(req.query);
    res.json({ success: true, data: await service.list(organizationId, query) });
  })
);

/**
 * @swagger
 * /api/v1/branches:
 *   post:
 *     summary: createBranch
 *     operationId: postBranches
 *     description: Create a branch; its code (BR-0001, BR-0002, ...) is generated by the server
 *     tags: [branches]
 *     security:
 *       - BearerAuth: []
 *     responses:
 *       201: { description: Created branch }
 *       409: { description: A branch with this name already exists }
 */
router.post(
  '/',
  authenticate,
  requirePermission('users:manage'),
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId, actorId } = orgContextOf(req);
    const dto = CreateBranchSchema.parse(req.body);
    res
      .status(201)
      .json({ success: true, data: await service.create(organizationId, dto, actorId) });
  })
);

/**
 * @swagger
 * /api/v1/branches/{id}:
 *   get:
 *     summary: getBranchById
 *     operationId: getBranchesById
 *     description: Get a branch
 *     tags: [branches]
 *     security:
 *       - BearerAuth: []
 *     responses:
 *       200: { description: Branch }
 *       404: { description: Not found }
 */
router.get(
  '/:id',
  authenticate,
  requirePermission('users:read', 'users:manage'),
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = orgContextOf(req);
    const { id } = IdParamSchema.parse(req.params);
    res.json({ success: true, data: await service.get(organizationId, id) });
  })
);

/**
 * @swagger
 * /api/v1/branches/{id}:
 *   put:
 *     summary: updateBranch
 *     operationId: putBranchesById
 *     description: Update a branch; the code is immutable
 *     tags: [branches]
 *     security:
 *       - BearerAuth: []
 *     responses:
 *       200: { description: Updated branch }
 */
router.put(
  '/:id',
  authenticate,
  requirePermission('users:manage'),
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId, actorId } = orgContextOf(req);
    const { id } = IdParamSchema.parse(req.params);
    const dto = UpdateBranchSchema.parse(req.body);
    res.json({ success: true, data: await service.update(organizationId, id, dto, actorId) });
  })
);

/**
 * @swagger
 * /api/v1/branches/{id}:
 *   delete:
 *     summary: deleteBranch
 *     operationId: deleteBranchesById
 *     description: Soft-delete a branch and unassign its users
 *     tags: [branches]
 *     security:
 *       - BearerAuth: []
 *     responses:
 *       200: { description: Deleted }
 *       409: { description: The head office cannot be deleted }
 */
router.delete(
  '/:id',
  authenticate,
  requirePermission('users:manage'),
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId, actorId } = orgContextOf(req);
    const { id } = IdParamSchema.parse(req.params);
    res.json({ success: true, data: await service.remove(organizationId, id, actorId) });
  })
);

export default router;
