import { BranchItem, SaveBranchRequest } from '../../../../../shared/models/iam-admin.model';
import { FormField, FormValues } from '../../../../iam/shared/iam-form-dialog.component';

const text = (v: FormValues, key: string): string | null => {
  const value = v[key];
  return typeof value === 'string' && value.trim() ? value.trim() : null;
};

/**
 * Create/edit/view form for a branch. The code is generated by the server and never
 * editable, so it is shown read-only and only once it exists.
 */
export const branchFields = (current?: BranchItem, readOnly = false): FormField[] => [
  {
    key: 'code',
    label: 'Branch code',
    type: 'text',
    disabled: true,
    value: current?.code ?? '',
    placeholder: 'Generated automatically on save',
    hint: current ? undefined : 'Assigned in sequence, e.g. BR-0001. It cannot be changed.',
  },
  {
    key: 'name',
    label: 'Branch name',
    type: 'text',
    required: true,
    maxLength: 120,
    disabled: readOnly,
    value: current?.name,
    placeholder: 'e.g. Chennai Office',
  },
  {
    key: 'status',
    label: 'Status',
    type: 'select',
    required: true,
    disabled: readOnly,
    value: current?.status ?? 'active',
    options: [
      { label: 'Active', value: 'active' },
      { label: 'Inactive', value: 'inactive' },
    ],
  },
  {
    key: 'isHeadOffice',
    label: 'Head office',
    type: 'toggle',
    // Clearing head office is done by promoting another branch, so it is locked once set.
    disabled: readOnly || current?.isHeadOffice === true,
    value: current?.isHeadOffice ?? false,
    hint: 'Only one branch can be the head office; setting this moves it from the current one.',
  },
  {
    key: 'address',
    label: 'Address',
    type: 'textarea',
    maxLength: 300,
    disabled: readOnly,
    value: current?.address,
  },
  {
    key: 'city',
    label: 'City',
    type: 'text',
    maxLength: 100,
    disabled: readOnly,
    value: current?.city,
  },
  {
    key: 'state',
    label: 'State / Province',
    type: 'text',
    maxLength: 100,
    disabled: readOnly,
    value: current?.state,
  },
  {
    key: 'country',
    label: 'Country',
    type: 'text',
    maxLength: 100,
    disabled: readOnly,
    value: current?.country,
  },
  {
    key: 'pincode',
    label: 'Postal code',
    type: 'text',
    maxLength: 12,
    disabled: readOnly,
    value: current?.pincode,
    pattern: { regex: /^[A-Za-z0-9 -]*$/, message: 'Letters, digits, spaces and - only.' },
  },
  {
    key: 'phone',
    label: 'Phone',
    type: 'text',
    maxLength: 20,
    disabled: readOnly,
    value: current?.phone,
    placeholder: '+91 44 1234 5678',
    pattern: { regex: /^[0-9+()\s-]*$/, message: 'Digits, spaces and + ( ) - only.' },
  },
  {
    key: 'email',
    label: 'Email',
    type: 'email',
    maxLength: 254,
    disabled: readOnly,
    value: current?.email,
    placeholder: 'branch@company.com',
  },
];

export const toBranchRequest = (v: FormValues): SaveBranchRequest => ({
  name: text(v, 'name') ?? '',
  status: v['status'] === 'inactive' ? 'inactive' : 'active',
  isHeadOffice: v['isHeadOffice'] === true,
  address: text(v, 'address'),
  city: text(v, 'city'),
  state: text(v, 'state'),
  country: text(v, 'country'),
  pincode: text(v, 'pincode'),
  phone: text(v, 'phone'),
  email: text(v, 'email'),
});
